server:
  port: 8085
  servlet:
    context-path: /
    encoding:
     charset: UTF-8
     enabled: true
     force: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3550/gb?serverTimezone=Asia/Seoul
    username: gb
    password: gb
    
  jpa:
    open-in-view: true
    hibernate:
      naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

        

    
    
    
    #hibernate:
      #ddl-auto: update
      #naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     # use-new-id-generator-mappings: false
    #show-sql: true
   # properties:
    #  hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 263945259562-99nrd6n4uhiqrgibh539klqrcgt5q7h9.apps.googleusercontent.com
            client-secret: -LD5RP6O1NiVBtq535aMexx7
            scope:
            - email
            - profile
            
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  